Server:
  port: 8001
mybatis:
  type-handlers-package: com.liuencier.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: spring-cloud-provider-dept
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/springcloudci?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver # 根据数据库不同配置
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-dept-8001
# 配置 eureka 的显示信息
info:
  app.name: cier.site
  company.name: cvte.site